trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
    displayName: 'Install .NET 8 SDK'

  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build --configuration Release --no-restore
    displayName: 'Build solution'

  - script: dotnet test --configuration Release --no-build --logger trx
    displayName: 'Run unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true
    displayName: 'Publish test results'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
    displayName: 'Publish API'

  # Publish API build output
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'api'
      displayName: 'Publish API build artifacts'

  # Publish Kubernetes manifests
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'manifests'
      artifactName: 'manifests'
      displayName: 'Publish Kubernetes manifests'